name: TrickorCollect
version: '1.0-SNAPSHOT'
main: com.meao0525.trickorcollect.TrickorCollect
api-version: 1.18
authors: [ meao0525 ]

commands:
  tc:
    description:
      TRICK OR COLLECT game command
    usage:
      /<command> help
    permission:
      default-permission
    permission-message:
      omae niha murida w